package main

type LanguageMap struct {
	Code string
	Name string
}

var LanguageMaps = []*LanguageMap{
	&LanguageMap{"auto", "Auto Detect Type"},
	&LanguageMap{"text", "Plain Text"},
	&LanguageMap{"-", "-"},
	&LanguageMap{"applescript", "AppleScript"},
	&LanguageMap{"boxnote", "Boxnote"},
	&LanguageMap{"c", "C"},
	&LanguageMap{"csharp", "C#"},
	&LanguageMap{"cpp", "C++"},
	&LanguageMap{"css", "CSS"},
	&LanguageMap{"diff", "Diff"},
	&LanguageMap{"csv", "CSV"},
	&LanguageMap{"clojure", "Clojure"},
	&LanguageMap{"coffeescript", "CoffeeScript"},
	&LanguageMap{"cfm", "ColdFusion"},
	&LanguageMap{"crystal", "Crystal"},
	&LanguageMap{"cypher", "Cypher"},
	&LanguageMap{"d", "D"},
	&LanguageMap{"dart", "Dart"},
	&LanguageMap{"diff", "Diff"},
	&LanguageMap{"dockerfile", "Docker"},
	&LanguageMap{"erlang", "Erlang"},
	&LanguageMap{"fsharp", "F#"},
	&LanguageMap{"fortran", "Fortran"},
	&LanguageMap{"gherkin", "Gherkin"},
	&LanguageMap{"go", "Go"},
	&LanguageMap{"groovy", "Groovy"},
	&LanguageMap{"html", "HTML"},
	&LanguageMap{"handlebars", "Handlebars"},
	&LanguageMap{"haskell", "Haskell"},
	&LanguageMap{"haxe", "Haxe"},
	&LanguageMap{"java", "Java"},
	&LanguageMap{"javascript", "JavaScript/JSON"},
	&LanguageMap{"julia", "Julia"},
	&LanguageMap{"kotlin", "Kotlin"},
	&LanguageMap{"latex", "LaTeX/sTeX"},
	&LanguageMap{"lisp", "Lisp"},
	&LanguageMap{"lua", "Lua"},
	&LanguageMap{"matlab", "MATLAB"},
	&LanguageMap{"mumps", "MUMPS"},
	&LanguageMap{"markdown", "Markdown (raw)"},
	&LanguageMap{"ocaml", "OCaml"},
	&LanguageMap{"objc", "Objective-C"},
	&LanguageMap{"php", "PHP"},
	&LanguageMap{"pascal", "Pascal"},
	&LanguageMap{"perl", "Perl"},
	&LanguageMap{"pig", "Pig"},
	&LanguageMap{"post", "Post"},
	&LanguageMap{"powershell", "PowerShell"},
	&LanguageMap{"puppet", "Puppet"},
	&LanguageMap{"python", "Python"},
	&LanguageMap{"r", "R"},
	&LanguageMap{"ruby", "Ruby"},
	&LanguageMap{"rust", "Rust"},
	&LanguageMap{"sql", "SQL"},
	&LanguageMap{"sass", "Sass"},
	&LanguageMap{"scala", "Scala"},
	&LanguageMap{"scheme", "Scheme"},
	&LanguageMap{"shell", "Shell"},
	&LanguageMap{"smalltalk", "Smalltalk"},
	&LanguageMap{"swift", "Swift"},
	&LanguageMap{"tsv", "TSV"},
	&LanguageMap{"vb", "VB.NET"},
	&LanguageMap{"vbscript", "VBScript"},
	&LanguageMap{"velocity", "Velocity"},
	&LanguageMap{"yaml", "Verilog"},
	&LanguageMap{"verilog", "YAML"},
	&LanguageMap{"xml", "XML"},
	&LanguageMap{"yaml", "YAML"},
}
